### ISSUE TITLE
Error when running mkvirtualenv

### ISSUE THREAD

**Issue by julie777** [python-virtualenvwrapper/virtualenvwrapper#67]
When I run `mkvirtualenv -a projectdir projectname` I get the error below. The virtual environment is created, but missing the .project file. After I manually create the .project file the environment seems to work fine. I do not understand what the syntax error is referring to, so I cannot determine the solution. I do suspect that it has to do with path representation shifting to and from "C:\" and "/c/" in some place in the code.

I am running on Windows 10, using Git for Windows bash in Windows Terminal. 
Python311 is installed for my user into AppData and that version is run from bash, which explains all of the back-slashes in the error message.

```
created virtual environment CPython3.11.2.final.0-64 in 1564ms
  creator CPython3Windows(dest=C:\Users\julie\home\.venvs\3D-printer-profiles, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\julie\AppData\Local\pypa\virtualenv)
    added seed packages: pip==23.1.2, setuptools==67.7.2, wheel==0.40.0
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
virtualenvwrapper.user_scripts creating C:\Users\julie\home\.venvs\3D-printer-profiles\Scripts\predeactivate
virtualenvwrapper.user_scripts creating C:\Users\julie\home\.venvs\3D-printer-profiles\Scripts\postdeactivate
virtualenvwrapper.user_scripts creating C:\Users\julie\home\.venvs\3D-printer-profiles\Scripts\preactivate
virtualenvwrapper.user_scripts creating C:\Users\julie\home\.venvs\3D-printer-profiles\Scripts\postactivate
virtualenvwrapper.user_scripts creating C:\Users\julie\home\.venvs\3D-printer-profiles\Scripts\get_env_details
  File "<string>", line 1
    import os,sys; sys.stdout.write(os.path.abspath("C:\Users\julie\home\code\projects\3D-printer-profiles")+'\n')
                                                                                                           ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
Cannot associate virtualenv with "", it is not a directory
```

**Comment by dhellmann** [comment]
We don't really test virtualenvwrapper on Windows, so I wouldn't be surprised if there is an issue with path handling. In this case, there is a [bash function](https://github.com/python-virtualenvwrapper/virtualenvwrapper/blob/main/virtualenvwrapper.sh#L142) trying to use python to determine the real path, and it does look like that could be an issue if the input value uses Windows' backslashes instead of Unix's forward slashes.

I'm afraid I don't know enough about modern Windows or Git for Windows bash to offer a concrete solution. Is there some sort of tool for turning a Windows-style path into a Unix-style path? If there is, we could fix  `virtualenvwrapper_absolutepath` by doing the conversion. Otherwise, we would have to look at how to escape the backslashes properly.

**Comment by carltongibson** [comment]
I'm not sure this is really an addressable issue as it stands.

**Comment by dhellmann** [comment]
This ticket has been open for a while with no response, so I am closing it. Let us know if you are still having this problem.
